export {
  MagicAppsClient,
  AuthMode,
  AuthService,
  PaymentsService,
  EntitlementsService,
  DevicesService,
  AIService,
  EndpointsService,
  FilesService,
  NotificationsService,
  ProfilesService,
  AccountService,
  SettingsService,
  CatalogService,
  LookupTablesService,
  OwnerService,
  TemplatesService,
  EmailService,
} from "./client.js";
export type {
  MagicAppsConfig,
  AppInfo,
  Template,
  ApiResponse,
  PaginatedResponse,
  ChatMessage,
  ChatCompletionRequest,
  ChatCompletionChoice,
  TokenUsage,
  ChatCompletionResponse,
  EmbeddingData,
  EmbeddingResponse,
  GeneratedImage,
  ImageGenerationResponse,
  ModerationCategories,
  ModerationCategoryScores,
  ModerationResult,
  ModerationResponse,
  Device,
  DeviceCatalogResponse,
  RegistryApp,
  AuthTokenResponse,
  UserProfile,
  UpdateProfileData,
  PublicProfile,
  DeleteAccountRequest,
  AccountDataExport,
  ConsentPreferences,
  FileUploadUrl,
  StoredFile,
  CreateConversationOptions,
  Conversation,
  ConversationMessage,
  SendMessageOptions,
  SendMessageResponse,
  DeviceRegistration,
  SubscriptionTier,
  SubscriptionDetails,
  SubscriptionResponse,
  CustomerPortalResponse,
  EntitlementStatus,
  AppTier,
  TiersResponse,
  ChangeSubscriptionResponse,
  CheckoutSessionResponse,
  PaymentVerifyResponse,
  CreateUserTokenResponse,
  CreateImageTokenResponse,
  CreateTextTokenResponse,
  EmailTokenStatus,
} from "./types.js";
export { MagicAppsError, ApiError } from "./errors.js";
export {
  deprecated,
  warnDeprecated,
  type DeprecationOptions,
} from "./deprecation.js";
export {
  generateHmacSignature,
  verifyHmacSignature,
  type HmacSignatureHeaders,
} from "./hmac.js";
